In [1]:
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = sns.load_dataset('titanic')

In [3]:
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [4]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [6]:
df.drop(["deck", "embark_town", "alive", "who", "adult_male", "class"], axis = 1, inplace = True)

In [7]:
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  alone
0         0       3    male  22.0      1      0   7.2500        S  False
1         1       1  female  38.0      1      0  71.2833        C  False
2         1       3  female  26.0      0      0   7.9250        S   True
3         1       1  female  35.0      1      0  53.1000        S  False
4         0       3    male  35.0      0      0   8.0500        S   True

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   survived  891 non-null    int64  
 1   pclass    891 non-null    int64  
 2   sex       891 non-null    object 
 3   age       714 non-null    float64
 4   sibsp     891 non-null    int64  
 5   parch     891 non-null    int64  
 6   fare      891 non-null    float64
 7   embarked  889 non-null    object 
 8   alone     891 non-null    bool   
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 56.7+ KB


In [9]:
# we will fill the null values of age and embarked

In [10]:
df["age"].fillna(df["age"].mean(), inplace = True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   survived  891 non-null    int64  
 1   pclass    891 non-null    int64  
 2   sex       891 non-null    object 
 3   age       891 non-null    float64
 4   sibsp     891 non-null    int64  
 5   parch     891 non-null    int64  
 6   fare      891 non-null    float64
 7   embarked  889 non-null    object 
 8   alone     891 non-null    bool   
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 56.7+ KB


In [11]:
# CODE TO DROP A WHOLE ROW

In [12]:
df.dropna(subset = ["embarked"], inplace = True)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   survived  889 non-null    int64  
 1   pclass    889 non-null    int64  
 2   sex       889 non-null    object 
 3   age       889 non-null    float64
 4   sibsp     889 non-null    int64  
 5   parch     889 non-null    int64  
 6   fare      889 non-null    float64
 7   embarked  889 non-null    object 
 8   alone     889 non-null    bool   
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 63.4+ KB


In [14]:
# Now we have to predict survived or not, we will level encode

In [15]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [16]:
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  alone
0         0       3    male  22.0      1      0   7.2500        S  False
1         1       1  female  38.0      1      0  71.2833        C  False
2         1       3  female  26.0      0      0   7.9250        S   True
3         1       1  female  35.0      1      0  53.1000        S  False
4         0       3    male  35.0      0      0   8.0500        S   True

In [17]:
df['sex'] = le.fit_transform(df['sex'])
df['embarked'] = le.fit_transform(df['embarked'])


In [18]:
df = df.astype(int)

In [19]:
df.head()

survived  pclass  sex  age  sibsp  parch  fare  embarked  alone
0         0       3    1   22      1      0     7         2      0
1         1       1    0   38      1      0    71         0      0
2         1       3    0   26      0      0     7         2      1
3         1       1    0   35      1      0    53         2      0
4         0       3    1   35      0      0     8         2      1

In [20]:
X = df.drop("survived", axis = 1)
y = df["survived"]

In [21]:
from sklearn.model_selection import train_test_split


In [22]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

# Now we use logistic regression

In [23]:
from sklearn.linear_model import LogisticRegression

In [24]:
model = LogisticRegression()

model.fit(X_train,y_train)

LogisticRegression()

In [25]:
y_pred = model.predict(X_test)

In [26]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [27]:
accuracy_score(y_test, y_pred)

0.8163265306122449

In [28]:
confusion_matrix(y_test, y_pred)

array([[157,  27],
       [ 27,  83]])

In [29]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.85      0.85      0.85       184
           1       0.75      0.75      0.75       110

    accuracy                           0.82       294
   macro avg       0.80      0.80      0.80       294
weighted avg       0.82      0.82      0.82       294



# KNN (k nearest neighbour)

In [30]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [31]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.fit_transform(X_test)

In [32]:
from sklearn.neighbors import KNeighborsClassifier

In [33]:
knn_model = KNeighborsClassifier(n_neighbors= 5)
knn_model.fit(X_train,y_train)

KNeighborsClassifier()

In [34]:
y_pred_knn = knn_model.predict(X_test)


In [35]:
accuracy_score(y_test,y_pred_knn)

0.7040816326530612

In [36]:
confusion_matrix(y_test,y_pred_knn)

array([[147,  37],
       [ 50,  60]])

In [37]:
print(classification_report(y_test,y_pred_knn))

              precision    recall  f1-score   support

           0       0.75      0.80      0.77       184
           1       0.62      0.55      0.58       110

    accuracy                           0.70       294
   macro avg       0.68      0.67      0.68       294
weighted avg       0.70      0.70      0.70       294



# NAIVE BAYES'S IMPLEMENTATION

In [38]:
from sklearn.naive_bayes import GaussianNB

In [39]:
model_NB = GaussianNB()

In [40]:
model_NB.fit(X_train,y_train)

GaussianNB()

In [41]:
y_pred_NB = model_NB.predict(X_test)
y_pred_NB

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 1, 1])

In [42]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [43]:
accuracy_score(y_test,y_pred_NB)

0.7789115646258503

In [44]:
confusion_matrix(y_test,y_pred_NB)

array([[145,  39],
       [ 26,  84]])

In [45]:
print(classification_report(y_test,y_pred_NB))

              precision    recall  f1-score   support

           0       0.85      0.79      0.82       184
           1       0.68      0.76      0.72       110

    accuracy                           0.78       294
   macro avg       0.77      0.78      0.77       294
weighted avg       0.79      0.78      0.78       294



# DECISION TREES IMPLEMENTATION

In [46]:
df.head()

survived  pclass  sex  age  sibsp  parch  fare  embarked  alone
0         0       3    1   22      1      0     7         2      0
1         1       1    0   38      1      0    71         0      0
2         1       3    0   26      0      0     7         2      1
3         1       1    0   35      1      0    53         2      0
4         0       3    1   35      0      0     8         2      1

In [47]:
from sklearn.tree import DecisionTreeClassifier

In [48]:

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

DT_model = DecisionTreeClassifier()
DT_model.fit(X_train, y_train)




DecisionTreeClassifier()

In [49]:
y_pred_DT = DT_model.predict(X_test)

accuracy_score(y_test, y_pred_DT)

0.7865168539325843

In [50]:
confusion_matrix(y_test, y_pred_DT)

array([[139,  28],
       [ 29,  71]])

In [51]:
classification_report(y_test, y_pred_DT)

'              precision    recall  f1-score   support\n\n           0       0.83      0.83      0.83       167\n           1       0.72      0.71      0.71       100\n\n    accuracy                           0.79       267\n   macro avg       0.77      0.77      0.77       267\nweighted avg       0.79      0.79      0.79       267\n'

# SUPPORT VECTOR MACHINE (SVM)

In [52]:
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split

In [53]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
model_SVC = SVC(kernel = 'rbf')
model_SVC.fit(X_train,y_train)

SVC()

In [54]:
y_pred_SVC = model_SVC.predict(X_test)

In [55]:
accuracy_score(y_test,y_pred_SVC)

0.673469387755102

In [56]:
# non scaled performed average

In [57]:
model_SVC2 = SVC(kernel = 'rbf')
model_SVC2.fit(X_train_scaled,y_train)

SVC()

In [58]:
y_pred_SVC2 = model_SVC2.predict(X_test_scaled)

In [59]:
accuracy_score(y_test,y_pred_SVC2)

0.8197278911564626

In [60]:
# hence we can see that svm gives the best accuracy among all of these models using scaled dataset

In [61]:
confusion_matrix(y_test,y_pred_SVC2)

array([[160,  24],
       [ 29,  81]])

In [62]:
classification_report(y_test,y_pred_SVC2)

'              precision    recall  f1-score   support\n\n           0       0.85      0.87      0.86       184\n           1       0.77      0.74      0.75       110\n\n    accuracy                           0.82       294\n   macro avg       0.81      0.80      0.81       294\nweighted avg       0.82      0.82      0.82       294\n'

# LET'S SEE WHAT CROSS VALIDATION CAN DO

In [67]:
X = df.drop('survived', axis =1)
y = df['survived']

In [68]:
from sklearn.model_selection import cross_val_score 

In [70]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [77]:
scores = cross_val_score(model_SVC2, X_scaled,y,cv=5, scoring='accuracy')          # for svm model

In [72]:
print(scores)

[0.83146067 0.82022472 0.81460674 0.80898876 0.86440678]


In [73]:
print(scores.mean())

0.8279375357074844


In [78]:
scores = cross_val_score(knn_model, X_scaled,y,cv=5, scoring='accuracy')           # for knn model

In [75]:
print(scores)

[0.78651685 0.76404494 0.8258427  0.81460674 0.80225989]


In [76]:
print(scores.mean())

0.7986542245921411
